#include <ams_mel/abi.h>

#include <stddef.h>
#include <stdio.h>

#define VALUE(value) printf("%llu\n", (unsigned long long)(value))
#define LAYOUT(type) VALUE(sizeof(type)); VALUE(_Alignof(type))
#define FIELD(type, field) VALUE(offsetof(type, field))

int main(void)
{
    ams_mel_abi_version_v1 version = {0, 0};
    ams_mel_status_t (*submit_bit)(ams_mel_ir_c2 *, uint32_t,
        ams_mel_ir_return_request **, char *, size_t, size_t *) =
        ams_mel_ir_c2_submit_bit_noop;
    ams_mel_status_t (*wait_return)(const ams_mel_ir_return_request *, uint32_t,
        ams_mel_ir_return_result_v1 *, char *, size_t, size_t *) =
        ams_mel_ir_return_request_wait;
    ams_mel_status_t (*close_return)(ams_mel_ir_return_request **, char *,
        size_t, size_t *) = ams_mel_ir_return_request_close;
    (void)submit_bit; (void)wait_return; (void)close_return;
    ams_mel_status_t (*submit_mode)(ams_mel_ir_c2 *, const ams_mel_ir_mode_command_v1 *,
        ams_mel_ir_mode_request **, char *, size_t, size_t *) = ams_mel_ir_c2_submit_mode;
    ams_mel_status_t (*submit_full_bit)(ams_mel_ir_c2 *, const ams_mel_ir_bit_command_v1 *,
        ams_mel_ir_return_request **, char *, size_t, size_t *) = ams_mel_ir_c2_submit_bit;
    ams_mel_status_t (*submit_config)(ams_mel_ir_c2 *, const ams_mel_ir_config_set_command_v1 *,
        ams_mel_ir_return_request **, char *, size_t, size_t *) = ams_mel_ir_c2_submit_config_set;
    (void)submit_mode; (void)submit_full_bit; (void)submit_config;
    ams_mel_status_t (*metadata_open)(ams_mel_ir_c2 *, size_t, ams_mel_ir_c2_metadata **, char *, size_t, size_t *) = ams_mel_ir_c2_metadata_open;
    ams_mel_status_t (*metadata_receive)(ams_mel_ir_c2_metadata *, uint32_t, ams_mel_ir_c2_metadata_event **, char *, size_t, size_t *) = ams_mel_ir_c2_metadata_receive;
    ams_mel_status_t (*metadata_counters)(const ams_mel_ir_c2_metadata *, ams_mel_ir_c2_metadata_counters_v1 *, char *, size_t, size_t *) = ams_mel_ir_c2_metadata_get_counters;
    ams_mel_status_t (*metadata_close)(ams_mel_ir_c2_metadata **, char *, size_t, size_t *) = ams_mel_ir_c2_metadata_close;
    ams_mel_status_t (*event_view)(const ams_mel_ir_c2_metadata_event *, const ams_mel_ir_c2_metadata_event_v1 **, char *, size_t, size_t *) = ams_mel_ir_c2_metadata_event_view;
    ams_mel_status_t (*event_close)(ams_mel_ir_c2_metadata_event **, char *, size_t, size_t *) = ams_mel_ir_c2_metadata_event_close;
    (void)metadata_open; (void)metadata_receive; (void)metadata_counters; (void)metadata_close; (void)event_view; (void)event_close;
    ams_mel_status_t (*keepalive)(ams_mel_ir_c2 *, ams_mel_ir_return_request **, char *, size_t, size_t *) = ams_mel_ir_c2_send_keepalive;
    ams_mel_status_t (*submit_comms)(ams_mel_ir_c2 *, const ams_mel_ir_channel_comms_test_request_v1 *, ams_mel_ir_channel_comms_request **, char *, size_t, size_t *) = ams_mel_ir_c2_submit_comms_test;
    ams_mel_status_t (*wait_comms)(const ams_mel_ir_channel_comms_request *, uint32_t, ams_mel_ir_channel_comms_test_result_v1 *, char *, size_t, size_t *) = ams_mel_ir_channel_comms_request_wait;
    ams_mel_status_t (*close_comms)(ams_mel_ir_channel_comms_request **, char *, size_t, size_t *) = ams_mel_ir_channel_comms_request_close;
    ams_mel_status_t (*register_comms)(ams_mel_ir_c2_metadata *, char *, size_t, size_t *) = ams_mel_ir_c2_metadata_register_comms_test;
    ams_mel_status_t (*get_cap)(ams_mel_ir_c2 *, ams_mel_ir_channel_capability **, char *, size_t, size_t *) = ams_mel_ir_c2_get_capabilities;
    ams_mel_status_t (*view_cap)(const ams_mel_ir_channel_capability *, const ams_mel_ir_channel_capability_v1 **, char *, size_t, size_t *) = ams_mel_ir_channel_capability_view;
    ams_mel_status_t (*close_cap)(ams_mel_ir_channel_capability **, char *, size_t, size_t *) = ams_mel_ir_channel_capability_close;
    (void)keepalive; (void)submit_comms; (void)wait_comms; (void)close_comms; (void)register_comms; (void)get_cap; (void)view_cap; (void)close_cap;
    ams_mel_status_t (*health_open)(const ams_mel_session *, const ams_mel_ir_health_config_v1 *, ams_mel_ir_health **, char *, size_t, size_t *) = ams_mel_ir_health_open;
    ams_mel_status_t (*health_enable)(ams_mel_ir_health *, char *, size_t, size_t *) = ams_mel_ir_health_enable;
    ams_mel_status_t (*health_cap)(ams_mel_ir_health *, ams_mel_ir_channel_capability **, char *, size_t, size_t *) = ams_mel_ir_health_get_capabilities;
    ams_mel_status_t (*health_close)(ams_mel_ir_health **, char *, size_t, size_t *) = ams_mel_ir_health_close;
    ams_mel_status_t (*health_metadata_open)(ams_mel_ir_health *, size_t, ams_mel_ir_health_metadata **, char *, size_t, size_t *) = ams_mel_ir_health_metadata_open;
    ams_mel_status_t (*health_receive)(ams_mel_ir_health_metadata *, uint32_t, ams_mel_ir_health_metadata_event **, char *, size_t, size_t *) = ams_mel_ir_health_metadata_receive;
    ams_mel_status_t (*health_counters)(const ams_mel_ir_health_metadata *, ams_mel_ir_metadata_counters_v1 *, char *, size_t, size_t *) = ams_mel_ir_health_metadata_get_counters;
    ams_mel_status_t (*health_metadata_close)(ams_mel_ir_health_metadata **, char *, size_t, size_t *) = ams_mel_ir_health_metadata_close;
    ams_mel_status_t (*health_view)(const ams_mel_ir_health_metadata_event *, const ams_mel_ir_health_metadata_event_v1 **, char *, size_t, size_t *) = ams_mel_ir_health_metadata_event_view;
    ams_mel_status_t (*health_event_close)(ams_mel_ir_health_metadata_event **, char *, size_t, size_t *) = ams_mel_ir_health_metadata_event_close;
    (void)health_open; (void)health_enable; (void)health_cap; (void)health_close; (void)health_metadata_open; (void)health_receive; (void)health_counters; (void)health_metadata_close; (void)health_view; (void)health_event_close;
    ams_mel_status_t (*image_cap)(ams_mel_ir_stream *, ams_mel_ir_channel_capability **, char *, size_t, size_t *) = ams_mel_ir_stream_get_capabilities;
    ams_mel_status_t (*image_open)(ams_mel_ir_stream *, size_t, ams_mel_ir_image_metadata **, char *, size_t, size_t *) = ams_mel_ir_image_metadata_open;
    ams_mel_status_t (*image_receive)(ams_mel_ir_image_metadata *, uint32_t, ams_mel_ir_image_metadata_event **, char *, size_t, size_t *) = ams_mel_ir_image_metadata_receive;
    ams_mel_status_t (*image_counters)(const ams_mel_ir_image_metadata *, ams_mel_ir_metadata_counters_v1 *, char *, size_t, size_t *) = ams_mel_ir_image_metadata_get_counters;
    ams_mel_status_t (*image_close)(ams_mel_ir_image_metadata **, char *, size_t, size_t *) = ams_mel_ir_image_metadata_close;
    ams_mel_status_t (*image_view)(const ams_mel_ir_image_metadata_event *, const ams_mel_ir_image_metadata_event_v1 **, char *, size_t, size_t *) = ams_mel_ir_image_metadata_event_view;
    ams_mel_status_t (*image_event_close)(ams_mel_ir_image_metadata_event **, char *, size_t, size_t *) = ams_mel_ir_image_metadata_event_close;
    ams_mel_status_t (*navigation_submit)(ams_mel_ir_stream *, const ams_mel_navigation_report_v1 *, ams_mel_ir_navigation_request **, char *, size_t, size_t *) = ams_mel_ir_stream_submit_navigation_report;
    ams_mel_status_t (*navigation_wait)(const ams_mel_ir_navigation_request *, uint32_t, ams_mel_ir_navigation_result_v1 *, char *, size_t, size_t *) = ams_mel_ir_navigation_request_wait;
    ams_mel_status_t (*navigation_close)(ams_mel_ir_navigation_request **, char *, size_t, size_t *) = ams_mel_ir_navigation_request_close;
    (void)image_cap; (void)image_open; (void)image_receive; (void)image_counters; (void)image_close; (void)image_view; (void)image_event_close;
    (void)navigation_submit; (void)navigation_wait; (void)navigation_close;

    VALUE(AMS_MEL_OK); VALUE(AMS_MEL_INVALID_ARGUMENT);
    VALUE(AMS_MEL_LIBRARY_LOAD_FAILED); VALUE(AMS_MEL_SYMBOL_NOT_FOUND);
    VALUE(AMS_MEL_FACTORY_FAILED); VALUE(AMS_MEL_INITIALIZATION_FAILED);
    VALUE(AMS_MEL_PROVIDER_EXCEPTION); VALUE(AMS_MEL_BUFFER_TOO_SMALL);
    VALUE(AMS_MEL_INTERNAL_ERROR); VALUE(AMS_MEL_TIMEOUT);
    VALUE(AMS_MEL_STREAM_STOPPED); VALUE(AMS_MEL_PROVIDER_FAILED);
    VALUE(AMS_MEL_COMMAND_REJECTED);
    VALUE(AMS_MEL_IR_CHANNEL_IRST_IMAGE);
    VALUE(AMS_MEL_IR_CHANNEL_COMMAND_AND_CONTROL);
    VALUE(AMS_MEL_IR_MFA_MODE_UNUSED); VALUE(AMS_MEL_IR_MFA_MODE_TASK_SCHED);
    VALUE(AMS_MEL_IR_MFA_MODE_SCAN_VOLUME_SCHED);
    VALUE(AMS_MEL_IR_MFA_MODE_SCAN_BAR_SCHED);
    VALUE(AMS_MEL_IR_MFA_STATE_NOT_SET); VALUE(AMS_MEL_IR_MFA_STATE_UNKNOWN);
    VALUE(AMS_MEL_IR_MFA_STATE_NOT_INSTALLED); VALUE(AMS_MEL_IR_MFA_STATE_OFF);
    VALUE(AMS_MEL_IR_MFA_STATE_PRE_INITIALIZATION); VALUE(AMS_MEL_IR_MFA_STATE_INITIALIZATION);
    VALUE(AMS_MEL_IR_MFA_STATE_STANDBY); VALUE(AMS_MEL_IR_MFA_STATE_OPERATE);
    VALUE(AMS_MEL_IR_MFA_STATE_OPERATE_RX_ONLY); VALUE(AMS_MEL_IR_MFA_STATE_OPERATE_TX_ONLY);
    VALUE(AMS_MEL_IR_MFA_STATE_MAINTENANCE); VALUE(AMS_MEL_IR_MFA_STATE_CALIBRATION);
    VALUE(AMS_MEL_IR_MFA_STATE_INITIATED_BIT); VALUE(AMS_MEL_IR_MFA_STATE_SHUTDOWN);
    VALUE(AMS_MEL_IR_MFA_STATE_DEGRADED); VALUE(AMS_MEL_IR_MFA_STATE_MAX_EXCLUSIVE);
    VALUE(AMS_MEL_IR_COORD_FRAME_INERTIAL); VALUE(AMS_MEL_IR_COORD_FRAME_AIRCRAFT);
    VALUE(AMS_MEL_IR_DEGRADATION_CAPACITY); VALUE(AMS_MEL_IR_DEGRADATION_VOLUME);
    VALUE(AMS_MEL_IR_DEGRADATION_RANGE); VALUE(AMS_MEL_IR_DEGRADATION_REVISIT);
    VALUE(AMS_MEL_IR_RETURN_SUCCESS); VALUE(AMS_MEL_IR_RETURN_BAD_POINTER);
    VALUE(AMS_MEL_IR_RETURN_FAIL); VALUE(AMS_MEL_IR_RETURN_NOT_SUPPORTED);
    VALUE(AMS_MEL_IR_RETURN_NOT_IMPLEMENTED);
    VALUE(AMS_MEL_ERROR_NONE); VALUE(AMS_MEL_ERROR_INVALID_ID);
    VALUE(AMS_MEL_ERROR_INVALID_STATE); VALUE(AMS_MEL_ERROR_INVALID_PARAMETERS);
    VALUE(AMS_MEL_ERROR_INSUFFICIENT_PERMISSIONS);
    VALUE(AMS_MEL_ERROR_INSUFFICIENT_RESOURCES);
    VALUE(AMS_MEL_ERROR_INSUFFICIENT_LOCAL_RESOURCES);
    VALUE(AMS_MEL_ERROR_INSUFFICIENT_REMOTE_RESOURCES);
    VALUE(AMS_MEL_ERROR_UNSUPPORTED);
    VALUE(AMS_MEL_IR_PIXEL_MONO);
    VALUE(AMS_MEL_IR_IMAGE_STARING); VALUE(AMS_MEL_IR_IMAGE_SCANNING);
    VALUE(AMS_MEL_IR_FLIP_NONE); VALUE(AMS_MEL_IR_FLIP_VERTICAL);
    VALUE(AMS_MEL_IR_FLIP_HORIZONTAL); VALUE(AMS_MEL_IR_FLIP_BOTH);

    LAYOUT(ams_mel_abi_version_v1);
    FIELD(ams_mel_abi_version_v1, major); FIELD(ams_mel_abi_version_v1, minor);
    LAYOUT(ams_mel_provider_version_v1);
    FIELD(ams_mel_provider_version_v1, api_version);
    FIELD(ams_mel_provider_version_v1, library_version);
    FIELD(ams_mel_provider_version_v1, vendor);
    FIELD(ams_mel_provider_version_v1, vendor_capacity);
    FIELD(ams_mel_provider_version_v1, vendor_required);
    FIELD(ams_mel_provider_version_v1, description);
    FIELD(ams_mel_provider_version_v1, description_capacity);
    FIELD(ams_mel_provider_version_v1, description_required);
    LAYOUT(ams_mel_string_view_v1);
    FIELD(ams_mel_string_view_v1, data); FIELD(ams_mel_string_view_v1, size);
    LAYOUT(ams_mel_u32_span_v1); FIELD(ams_mel_u32_span_v1, data); FIELD(ams_mel_u32_span_v1, size);
    LAYOUT(ams_mel_string_view_span_v1); FIELD(ams_mel_string_view_span_v1, data); FIELD(ams_mel_string_view_span_v1, size);
    LAYOUT(ams_mel_ir_scan_type_v1); FIELD(ams_mel_ir_scan_type_v1, continuous_scan); FIELD(ams_mel_ir_scan_type_v1, returning); FIELD(ams_mel_ir_scan_type_v1, agile_scan);
    LAYOUT(ams_mel_ir_scan_param_v1);
    FIELD(ams_mel_ir_scan_param_v1, elevation_defined_with_range_and_altitude); FIELD(ams_mel_ir_scan_param_v1, center_az_rad); FIELD(ams_mel_ir_scan_param_v1, center_el_rad); FIELD(ams_mel_ir_scan_param_v1, center_frame_ref_el); FIELD(ams_mel_ir_scan_param_v1, center_frame_ref_az); FIELD(ams_mel_ir_scan_param_v1, scan_width_rad); FIELD(ams_mel_ir_scan_param_v1, scan_height_rad); FIELD(ams_mel_ir_scan_param_v1, scan_type); FIELD(ams_mel_ir_scan_param_v1, scan_id); FIELD(ams_mel_ir_scan_param_v1, scan_rate_rad_per_second); FIELD(ams_mel_ir_scan_param_v1, preferred_revisit_interval_seconds); FIELD(ams_mel_ir_scan_param_v1, required_revisit_interval_seconds); FIELD(ams_mel_ir_scan_param_v1, max_range_of_interest_m); FIELD(ams_mel_ir_scan_param_v1, min_range_of_interest_m); FIELD(ams_mel_ir_scan_param_v1, elevation_scan_center_altitude_m); FIELD(ams_mel_ir_scan_param_v1, elevation_scan_center_range_m); FIELD(ams_mel_ir_scan_param_v1, degradation_method);
    LAYOUT(ams_mel_ir_mode_command_v1); FIELD(ams_mel_ir_mode_command_v1, command_id); FIELD(ams_mel_ir_mode_command_v1, state); FIELD(ams_mel_ir_mode_command_v1, mode); FIELD(ams_mel_ir_mode_command_v1, scan_parameters);
    LAYOUT(ams_mel_ir_bit_command_v1); FIELD(ams_mel_ir_bit_command_v1, command_id); FIELD(ams_mel_ir_bit_command_v1, initiate_bit_ids); FIELD(ams_mel_ir_bit_command_v1, cancel_bit_ids); FIELD(ams_mel_ir_bit_command_v1, clear_fault_codes);
    LAYOUT(ams_mel_ir_config_set_command_v1); FIELD(ams_mel_ir_config_set_command_v1, command_id); FIELD(ams_mel_ir_config_set_command_v1, system_time_ns); FIELD(ams_mel_ir_config_set_command_v1, config);
    LAYOUT(ams_mel_uci_id_v1);
    FIELD(ams_mel_uci_id_v1, uuid); FIELD(ams_mel_uci_id_v1, descriptive_label);
    LAYOUT(ams_mel_component_location_v1);
    FIELD(ams_mel_component_location_v1, offset_x_m);
    FIELD(ams_mel_component_location_v1, offset_y_m);
    FIELD(ams_mel_component_location_v1, offset_z_m);
    FIELD(ams_mel_component_location_v1, key);
    FIELD(ams_mel_component_location_v1, system_name);
    LAYOUT(ams_mel_ir_stream_config_v1);
    FIELD(ams_mel_ir_stream_config_v1, channel_type);
    FIELD(ams_mel_ir_stream_config_v1, channel_id);
    FIELD(ams_mel_ir_stream_config_v1, platform_id);
    FIELD(ams_mel_ir_stream_config_v1, sensor_location);
    FIELD(ams_mel_ir_stream_config_v1, buffer_count);
    FIELD(ams_mel_ir_stream_config_v1, buffer_size);
    FIELD(ams_mel_ir_stream_config_v1, queue_capacity);
    LAYOUT(ams_mel_ir_c2_config_v1);
    FIELD(ams_mel_ir_c2_config_v1, channel_type);
    FIELD(ams_mel_ir_c2_config_v1, channel_id);
    FIELD(ams_mel_ir_c2_config_v1, platform_id);
    FIELD(ams_mel_ir_c2_config_v1, sensor_location);
    LAYOUT(ams_mel_ir_mode_result_v1);
    FIELD(ams_mel_ir_mode_result_v1, mode);
    FIELD(ams_mel_ir_mode_result_v1, error_code);
    LAYOUT(ams_mel_ir_return_result_v1);
    FIELD(ams_mel_ir_return_result_v1, value);
    FIELD(ams_mel_ir_return_result_v1, error_code);
    LAYOUT(ams_mel_ir_frame_v1);
    FIELD(ams_mel_ir_frame_v1, system_time_ns);
    FIELD(ams_mel_ir_frame_v1, integration_time_ns);
    FIELD(ams_mel_ir_frame_v1, width); FIELD(ams_mel_ir_frame_v1, height);
    FIELD(ams_mel_ir_frame_v1, bits_per_pixel);
    FIELD(ams_mel_ir_frame_v1, number_of_bands);
    FIELD(ams_mel_ir_frame_v1, horizontal_fov_rad);
    FIELD(ams_mel_ir_frame_v1, vertical_fov_rad);
    FIELD(ams_mel_ir_frame_v1, pixel_format);
    FIELD(ams_mel_ir_frame_v1, frame_id);
    FIELD(ams_mel_ir_frame_v1, subframe_id);
    FIELD(ams_mel_ir_frame_v1, subframe_total);
    FIELD(ams_mel_ir_frame_v1, image_type);
    FIELD(ams_mel_ir_frame_v1, image_flip);
    FIELD(ams_mel_ir_frame_v1, image_flags);
    FIELD(ams_mel_ir_frame_v1, dither_row);
    FIELD(ams_mel_ir_frame_v1, dither_column);
    FIELD(ams_mel_ir_frame_v1, row_offset);
    FIELD(ams_mel_ir_frame_v1, column_offset);
    FIELD(ams_mel_ir_frame_v1, band_index);
    FIELD(ams_mel_ir_frame_v1, reserved);
    FIELD(ams_mel_ir_frame_v1, pixels);
    FIELD(ams_mel_ir_frame_v1, pixel_capacity);
    FIELD(ams_mel_ir_frame_v1, pixel_required);
    LAYOUT(ams_mel_ir_stream_counters_v1);
    FIELD(ams_mel_ir_stream_counters_v1, frames_received);
    FIELD(ams_mel_ir_stream_counters_v1, frames_dropped_queue_full);
    FIELD(ams_mel_ir_stream_counters_v1, malformed_or_unsupported_frames);
    VALUE(AMS_MEL_IR_C2_METADATA_COMMAND_STATUS); VALUE(AMS_MEL_IR_C2_METADATA_BIT_CONFIGURATION); VALUE(AMS_MEL_IR_C2_METADATA_BIT_STATUS);
    VALUE(AMS_MEL_IR_IMAGE_METADATA_BAD_PIXEL_LIST); VALUE(AMS_MEL_IR_IMAGE_METADATA_LINE_OF_SIGHT_REPORT); VALUE(AMS_MEL_IR_IMAGE_METADATA_LINE_OF_SIGHT_EULER); VALUE(AMS_MEL_IR_IMAGE_METADATA_NAVIGATION_RESPONSE); VALUE(AMS_MEL_IR_BAD_PIXEL_REASON_UNKNOWN);
    VALUE(AMS_MEL_IR_COMMAND_NOT_SET); VALUE(AMS_MEL_IR_COMMAND_RECEIVED); VALUE(AMS_MEL_IR_COMMAND_ACCEPTED); VALUE(AMS_MEL_IR_COMMAND_REJECTED); VALUE(AMS_MEL_IR_COMMAND_CANCELLED);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_NOT_SET);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CONSTRAINT_ATTEMPTS);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CONSTRAINT_ENDURANCE);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CONSTRAINT_CLASSIFICATION);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CONSTRAINT_FOR_FOV_LIMIT);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CONSTRAINT_GATING);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CONSTRAINT_MANEUVER_LIMIT);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CONSTRAINT_OP);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CONSTRAINT_OCCLUSION);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CAPABILITY_RANGE);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CAPABILITY_PERFORMANCE);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CONSTRAINT_RF);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CONSTRAINT_ROUTE);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CONSTRAINT_SAFETY);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CONSTRAINT_TARGET_ANGLE);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CONSTRAINT_TIME);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CONSTRAINT_SYSTEM);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_INFEASIBLE_ROUTE);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_MISSION_EVENT);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_STATE_OR_SETTINGS);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_STATE_OR_SETTINGS_CHANGE);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_SYSTEM_UNAVAILABLE);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_SYSTEM_FAULT);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_SYSTEM_CONFLICT);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_SUBSYSTEM_UNAVAILABLE);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_SUBSYSTEM_FAULT);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CAPABILITY_FAULT);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CAPABILITY_PRECEDENCE);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CAPABILITY_UNAVAILABLE);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_INSUFFICIENT_RESOURCES);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_RANKING);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_WEATHER);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_INELIGIBLE_CONTROL_SOURCE);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_DEPENDENCY_PREDECESSOR);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_DEPENDENCY_ALL_OR_NOTHING);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_DEPENDENCY_EITHER_OR);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_INIT_CRITERIA_NOT_MET);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_UNKNOWN_ID);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_INVALID_INPUT_PARAMETER);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_INPUT_OTHER);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_MDF_ACTIVATION_ERROR);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_MULTIPLE);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_CANCELLED);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_OTHER);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_UNKNOWN);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_ABORTED);
    VALUE(AMS_MEL_IR_CANNOT_COMPLY_ALIGNMENT_MANEUVER);
    VALUE(AMS_MEL_BIT_CONTROL_NOT_SET); VALUE(AMS_MEL_BIT_CONTROL_SUBSYSTEM_BIT_COMMAND); VALUE(AMS_MEL_BIT_CONTROL_SUBSYSTEM_STATE_COMMAND); VALUE(AMS_MEL_BIT_CONTROL_SUBSYSTEM_INITIATED);
    VALUE(AMS_MEL_BIT_RESULT_NOT_SET); VALUE(AMS_MEL_BIT_RESULT_PASS); VALUE(AMS_MEL_BIT_RESULT_FAIL); VALUE(AMS_MEL_BIT_RESULT_INTERRUPTED); VALUE(AMS_MEL_BIT_RESULT_NOT_TESTED);
    VALUE(AMS_MEL_FAULT_SEVERITY_NOT_SET); VALUE(AMS_MEL_FAULT_SEVERITY_NOMINAL); VALUE(AMS_MEL_FAULT_SEVERITY_CAUTION); VALUE(AMS_MEL_FAULT_SEVERITY_WARNING); VALUE(AMS_MEL_FAULT_SEVERITY_FAILED);
    VALUE(AMS_MEL_FAULT_STATE_NOT_SET); VALUE(AMS_MEL_FAULT_STATE_SET); VALUE(AMS_MEL_FAULT_STATE_CLEARED); VALUE(AMS_MEL_FAULT_STATE_UNKNOWN);
    ams_mel_status_t (*instr_open)(const ams_mel_session *, const ams_mel_ir_instrumentation_config_v1 *, ams_mel_ir_instrumentation **, char *, size_t, size_t *) = ams_mel_ir_instrumentation_open;
    ams_mel_status_t (*instr_enable)(ams_mel_ir_instrumentation *, char *, size_t, size_t *) = ams_mel_ir_instrumentation_enable;
    ams_mel_status_t (*instr_cap)(ams_mel_ir_instrumentation *, ams_mel_ir_channel_capability **, char *, size_t, size_t *) = ams_mel_ir_instrumentation_get_capabilities;
    ams_mel_status_t (*instr_submit)(ams_mel_ir_instrumentation *, const ams_mel_ir_instrumentation_level_command_v1 *, ams_mel_ir_instrumentation_request **, char *, size_t, size_t *) = ams_mel_ir_instrumentation_submit_level;
    ams_mel_status_t (*instr_wait)(const ams_mel_ir_instrumentation_request *, uint32_t, ams_mel_ir_instrumentation_result_v1 *, char *, size_t, size_t *) = ams_mel_ir_instrumentation_request_wait;
    ams_mel_status_t (*instr_req_close)(ams_mel_ir_instrumentation_request **, char *, size_t, size_t *) = ams_mel_ir_instrumentation_request_close;
    ams_mel_status_t (*instr_meta_open)(ams_mel_ir_instrumentation *, size_t, ams_mel_ir_instrumentation_metadata **, char *, size_t, size_t *) = ams_mel_ir_instrumentation_metadata_open;
    ams_mel_status_t (*instr_meta_recv)(ams_mel_ir_instrumentation_metadata *, uint32_t, ams_mel_ir_instrumentation_metadata_event **, char *, size_t, size_t *) = ams_mel_ir_instrumentation_metadata_receive;
    ams_mel_status_t (*instr_meta_counters)(const ams_mel_ir_instrumentation_metadata *, ams_mel_ir_metadata_counters_v1 *, char *, size_t, size_t *) = ams_mel_ir_instrumentation_metadata_get_counters;
    ams_mel_status_t (*instr_meta_close)(ams_mel_ir_instrumentation_metadata **, char *, size_t, size_t *) = ams_mel_ir_instrumentation_metadata_close;
    ams_mel_status_t (*instr_ev_view)(const ams_mel_ir_instrumentation_metadata_event *, const ams_mel_ir_instrumentation_metadata_event_v1 **, char *, size_t, size_t *) = ams_mel_ir_instrumentation_metadata_event_view;
    ams_mel_status_t (*instr_ev_close)(ams_mel_ir_instrumentation_metadata_event **, char *, size_t, size_t *) = ams_mel_ir_instrumentation_metadata_event_close;
    ams_mel_status_t (*instr_close)(ams_mel_ir_instrumentation **, char *, size_t, size_t *) = ams_mel_ir_instrumentation_close;
    (void)instr_open; (void)instr_enable; (void)instr_cap; (void)instr_submit;
    (void)instr_wait; (void)instr_req_close; (void)instr_meta_open; (void)instr_meta_recv;
    (void)instr_meta_counters; (void)instr_meta_close; (void)instr_ev_view;
    (void)instr_ev_close; (void)instr_close;
    ams_mel_status_t (*track_open)(const ams_mel_session *, const ams_mel_ir_track_config_v1 *, ams_mel_ir_track **, char *, size_t, size_t *) = ams_mel_ir_track_open;
    ams_mel_status_t (*track_enable)(ams_mel_ir_track *, char *, size_t, size_t *) = ams_mel_ir_track_enable;
    ams_mel_status_t (*track_caps)(ams_mel_ir_track *, ams_mel_ir_channel_capability **, char *, size_t, size_t *) = ams_mel_ir_track_get_capabilities;
    ams_mel_status_t (*track_close)(ams_mel_ir_track **, char *, size_t, size_t *) = ams_mel_ir_track_close;
    (void)track_open; (void)track_enable; (void)track_caps; (void)track_close;
    ams_mel_status_t (*track_meta_open)(ams_mel_ir_track *, size_t, ams_mel_ir_track_metadata **, char *, size_t, size_t *) = ams_mel_ir_track_metadata_open;
    ams_mel_status_t (*track_meta_recv)(ams_mel_ir_track_metadata *, uint32_t, ams_mel_ir_track_metadata_event **, char *, size_t, size_t *) = ams_mel_ir_track_metadata_receive;
    ams_mel_status_t (*track_meta_counters)(const ams_mel_ir_track_metadata *, ams_mel_ir_metadata_counters_v1 *, char *, size_t, size_t *) = ams_mel_ir_track_metadata_get_counters;
    ams_mel_status_t (*track_meta_close)(ams_mel_ir_track_metadata **, char *, size_t, size_t *) = ams_mel_ir_track_metadata_close;
    ams_mel_status_t (*track_ev_view)(const ams_mel_ir_track_metadata_event *, const ams_mel_ir_track_metadata_event_v1 **, char *, size_t, size_t *) = ams_mel_ir_track_metadata_event_view;
    ams_mel_status_t (*track_ev_close)(ams_mel_ir_track_metadata_event **, char *, size_t, size_t *) = ams_mel_ir_track_metadata_event_close;
    (void)track_meta_open; (void)track_meta_recv; (void)track_meta_counters;
    (void)track_meta_close; (void)track_ev_view; (void)track_ev_close;
    ams_mel_status_t (*track_submit)(ams_mel_ir_track *, const ams_mel_ir_track_data_update_v1 *, ams_mel_ir_track_update_request **, char *, size_t, size_t *) = ams_mel_ir_track_submit_update;
    ams_mel_status_t (*track_upd_wait)(const ams_mel_ir_track_update_request *, uint32_t, ams_mel_ir_track_update_result_v1 *, char *, size_t, size_t *) = ams_mel_ir_track_update_request_wait;
    ams_mel_status_t (*track_upd_close)(ams_mel_ir_track_update_request **, char *, size_t, size_t *) = ams_mel_ir_track_update_request_close;
    (void)track_submit; (void)track_upd_wait; (void)track_upd_close;
    ams_mel_status_t (*track_rsp_submit)(ams_mel_ir_track *, const ams_mel_ir_system_track_data_response_v1 *, ams_mel_ir_track_system_response_request **, char *, size_t, size_t *) = ams_mel_ir_track_submit_system_track_data_response;
    ams_mel_status_t (*track_rsp_wait)(const ams_mel_ir_track_system_response_request *, uint32_t, ams_mel_ir_track_system_response_result_v1 *, char *, size_t, size_t *) = ams_mel_ir_track_system_response_request_wait;
    ams_mel_status_t (*track_rsp_close)(ams_mel_ir_track_system_response_request **, char *, size_t, size_t *) = ams_mel_ir_track_system_response_request_close;
    (void)track_rsp_submit; (void)track_rsp_wait; (void)track_rsp_close;
#define RECORD(type, ...) LAYOUT(type); __VA_ARGS__
    RECORD(ams_mel_uci_id_span_v1, FIELD(ams_mel_uci_id_span_v1,data); FIELD(ams_mel_uci_id_span_v1,size));
    RECORD(ams_mel_ir_command_status_v1, FIELD(ams_mel_ir_command_status_v1,command_id); FIELD(ams_mel_ir_command_status_v1,state); FIELD(ams_mel_ir_command_status_v1,reason_id); FIELD(ams_mel_ir_command_status_v1,reason_description));
    RECORD(ams_mel_bit_type_v1, FIELD(ams_mel_bit_type_v1,bit_id); FIELD(ams_mel_bit_type_v1,accepted_interface); FIELD(ams_mel_bit_type_v1,bit_item_names); FIELD(ams_mel_bit_type_v1,subsystem_component_ids); FIELD(ams_mel_bit_type_v1,expected_duration_ns));
    RECORD(ams_mel_bit_type_span_v1, FIELD(ams_mel_bit_type_span_v1,data); FIELD(ams_mel_bit_type_span_v1,size));
    RECORD(ams_mel_bit_configuration_v1, FIELD(ams_mel_bit_configuration_v1,bit_types));
    RECORD(ams_mel_active_bit_v1, FIELD(ams_mel_active_bit_v1,bit_id); FIELD(ams_mel_active_bit_v1,estimated_completion_time_ns); FIELD(ams_mel_active_bit_v1,estimated_percent_complete));
    RECORD(ams_mel_active_bit_span_v1, FIELD(ams_mel_active_bit_span_v1,data); FIELD(ams_mel_active_bit_span_v1,size));
    RECORD(ams_mel_completed_bit_item_v1, FIELD(ams_mel_completed_bit_item_v1,bit_item_name); FIELD(ams_mel_completed_bit_item_v1,result); FIELD(ams_mel_completed_bit_item_v1,fail_reason));
    RECORD(ams_mel_completed_bit_item_span_v1, FIELD(ams_mel_completed_bit_item_span_v1,data); FIELD(ams_mel_completed_bit_item_span_v1,size));
    RECORD(ams_mel_completed_bit_v1, FIELD(ams_mel_completed_bit_v1,bit_id); FIELD(ams_mel_completed_bit_v1,time_tag_ns); FIELD(ams_mel_completed_bit_v1,result); FIELD(ams_mel_completed_bit_v1,fail_reason); FIELD(ams_mel_completed_bit_v1,bit_items));
    RECORD(ams_mel_completed_bit_span_v1, FIELD(ams_mel_completed_bit_span_v1,data); FIELD(ams_mel_completed_bit_span_v1,size));
    RECORD(ams_mel_fault_data_v1, FIELD(ams_mel_fault_data_v1,key); FIELD(ams_mel_fault_data_v1,value); FIELD(ams_mel_fault_data_v1,format); FIELD(ams_mel_fault_data_v1,units));
    RECORD(ams_mel_fault_data_span_v1, FIELD(ams_mel_fault_data_span_v1,data); FIELD(ams_mel_fault_data_span_v1,size));
    RECORD(ams_mel_fault_ambiguity_group_v1, FIELD(ams_mel_fault_ambiguity_group_v1,diagnostic_test_ids); FIELD(ams_mel_fault_ambiguity_group_v1,component_ids));
    RECORD(ams_mel_fault_ambiguity_group_span_v1, FIELD(ams_mel_fault_ambiguity_group_span_v1,data); FIELD(ams_mel_fault_ambiguity_group_span_v1,size));
    RECORD(ams_mel_fault_v1, FIELD(ams_mel_fault_v1,fault_id); FIELD(ams_mel_fault_v1,severity); FIELD(ams_mel_fault_v1,state); FIELD(ams_mel_fault_v1,fault_data); FIELD(ams_mel_fault_v1,detection_time_ns); FIELD(ams_mel_fault_v1,fault_code); FIELD(ams_mel_fault_v1,fault_description); FIELD(ams_mel_fault_v1,component_ids); FIELD(ams_mel_fault_v1,ambiguity_groups));
    RECORD(ams_mel_fault_span_v1, FIELD(ams_mel_fault_span_v1,data); FIELD(ams_mel_fault_span_v1,size));
    RECORD(ams_mel_bit_status_v1, FIELD(ams_mel_bit_status_v1,active_bits); FIELD(ams_mel_bit_status_v1,completed_bits); FIELD(ams_mel_bit_status_v1,faults));
    RECORD(ams_mel_ir_c2_metadata_event_v1, FIELD(ams_mel_ir_c2_metadata_event_v1,kind); FIELD(ams_mel_ir_c2_metadata_event_v1,command_status); FIELD(ams_mel_ir_c2_metadata_event_v1,bit_configuration); FIELD(ams_mel_ir_c2_metadata_event_v1,bit_status); FIELD(ams_mel_ir_c2_metadata_event_v1,channel_comms_test));
    RECORD(ams_mel_ir_c2_metadata_counters_v1, FIELD(ams_mel_ir_c2_metadata_counters_v1,events_received); FIELD(ams_mel_ir_c2_metadata_counters_v1,events_dropped_queue_full); FIELD(ams_mel_ir_c2_metadata_counters_v1,malformed_or_unsupported));
    RECORD(ams_mel_ir_bad_pixel_v1, FIELD(ams_mel_ir_bad_pixel_v1,row); FIELD(ams_mel_ir_bad_pixel_v1,column); FIELD(ams_mel_ir_bad_pixel_v1,reason));
    RECORD(ams_mel_ir_bad_pixel_span_v1, FIELD(ams_mel_ir_bad_pixel_span_v1,data); FIELD(ams_mel_ir_bad_pixel_span_v1,size));
    RECORD(ams_mel_ir_bad_pixel_list_v1, FIELD(ams_mel_ir_bad_pixel_list_v1,reported_size); FIELD(ams_mel_ir_bad_pixel_list_v1,reported_count); FIELD(ams_mel_ir_bad_pixel_list_v1,pixels));
    RECORD(ams_mel_ir_az_el_v1, FIELD(ams_mel_ir_az_el_v1,azimuth_rad); FIELD(ams_mel_ir_az_el_v1,elevation_rad));
    RECORD(ams_mel_ir_line_of_sight_report_v1, FIELD(ams_mel_ir_line_of_sight_report_v1,system_time_ns); FIELD(ams_mel_ir_line_of_sight_report_v1,pointing_angle); FIELD(ams_mel_ir_line_of_sight_report_v1,pointing_angle_rates); FIELD(ams_mel_ir_line_of_sight_report_v1,at_speed); FIELD(ams_mel_ir_line_of_sight_report_v1,in_tolerance); FIELD(ams_mel_ir_line_of_sight_report_v1,platform_attitude); FIELD(ams_mel_ir_line_of_sight_report_v1,validity_flag_bitfield); FIELD(ams_mel_ir_line_of_sight_report_v1,image_rotation_rad));
    RECORD(ams_mel_ir_line_of_sight_euler_v1, FIELD(ams_mel_ir_line_of_sight_euler_v1,system_time_ns); FIELD(ams_mel_ir_line_of_sight_euler_v1,attitude); FIELD(ams_mel_ir_line_of_sight_euler_v1,attitude_rates));
    RECORD(ams_mel_ir_navigation_response_v1, FIELD(ams_mel_ir_navigation_response_v1,system_time_ns); FIELD(ams_mel_ir_navigation_response_v1,command_id); FIELD(ams_mel_ir_navigation_response_v1,request_id));
    RECORD(ams_mel_ir_image_metadata_event_v1, FIELD(ams_mel_ir_image_metadata_event_v1,kind); FIELD(ams_mel_ir_image_metadata_event_v1,bad_pixel_list); FIELD(ams_mel_ir_image_metadata_event_v1,line_of_sight_report); FIELD(ams_mel_ir_image_metadata_event_v1,line_of_sight_euler); FIELD(ams_mel_ir_image_metadata_event_v1,navigation_response));
    RECORD(ams_mel_ir_channel_comms_test_report_v1, FIELD(ams_mel_ir_channel_comms_test_report_v1,command_id); FIELD(ams_mel_ir_channel_comms_test_report_v1,request_id));
    RECORD(ams_mel_ir_channel_comms_test_request_v1, FIELD(ams_mel_ir_channel_comms_test_request_v1,command_id); FIELD(ams_mel_ir_channel_comms_test_request_v1,channel_id); FIELD(ams_mel_ir_channel_comms_test_request_v1,request_id));
    RECORD(ams_mel_ir_channel_comms_test_result_v1, FIELD(ams_mel_ir_channel_comms_test_result_v1,command_id); FIELD(ams_mel_ir_channel_comms_test_result_v1,request_id); FIELD(ams_mel_ir_channel_comms_test_result_v1,error_code));
    RECORD(ams_mel_ir_band_info_v1, FIELD(ams_mel_ir_band_info_v1,type); FIELD(ams_mel_ir_band_info_v1,min_wavelength_m); FIELD(ams_mel_ir_band_info_v1,max_wavelength_m));
    RECORD(ams_mel_ir_band_info_span_v1, FIELD(ams_mel_ir_band_info_span_v1,data); FIELD(ams_mel_ir_band_info_span_v1,size));
    RECORD(ams_mel_ir_image_band_v1, FIELD(ams_mel_ir_image_band_v1,band_index); FIELD(ams_mel_ir_image_band_v1,bands));
    RECORD(ams_mel_ir_image_band_span_v1, FIELD(ams_mel_ir_image_band_span_v1,data); FIELD(ams_mel_ir_image_band_span_v1,size));
    RECORD(ams_mel_ir_channel_capability_v1, FIELD(ams_mel_ir_channel_capability_v1,channel_id); FIELD(ams_mel_ir_channel_capability_v1,height); FIELD(ams_mel_ir_channel_capability_v1,width); FIELD(ams_mel_ir_channel_capability_v1,bit_depth); FIELD(ams_mel_ir_channel_capability_v1,row_pitch); FIELD(ams_mel_ir_channel_capability_v1,buffer_size); FIELD(ams_mel_ir_channel_capability_v1,image_size); FIELD(ams_mel_ir_channel_capability_v1,number_of_bands); FIELD(ams_mel_ir_channel_capability_v1,pixel_format); FIELD(ams_mel_ir_channel_capability_v1,sensor_types); FIELD(ams_mel_ir_channel_capability_v1,platform_id); FIELD(ams_mel_ir_channel_capability_v1,sensor_location); FIELD(ams_mel_ir_channel_capability_v1,channel_types); FIELD(ams_mel_ir_channel_capability_v1,task_schedule_depth); FIELD(ams_mel_ir_channel_capability_v1,odc_available); FIELD(ams_mel_ir_channel_capability_v1,nuc_available); FIELD(ams_mel_ir_channel_capability_v1,metadata_capabilities); FIELD(ams_mel_ir_channel_capability_v1,image_bands); FIELD(ams_mel_ir_channel_capability_v1,nav_frames));
    RECORD(ams_mel_ir_health_config_v1, FIELD(ams_mel_ir_health_config_v1,channel_id); FIELD(ams_mel_ir_health_config_v1,channel_type); FIELD(ams_mel_ir_health_config_v1,platform_id); FIELD(ams_mel_ir_health_config_v1,sensor_location));
    RECORD(ams_mel_euler_v1, FIELD(ams_mel_euler_v1,roll); FIELD(ams_mel_euler_v1,pitch); FIELD(ams_mel_euler_v1,yaw));
    RECORD(ams_mel_foreign_key_v1, FIELD(ams_mel_foreign_key_v1,key); FIELD(ams_mel_foreign_key_v1,system_name));
    RECORD(ams_mel_installation_details_v1, FIELD(ams_mel_installation_details_v1,location); FIELD(ams_mel_installation_details_v1,orientation); FIELD(ams_mel_installation_details_v1,boresight));
    RECORD(ams_mel_temperature_status_v1, FIELD(ams_mel_temperature_status_v1,temperature_c); FIELD(ams_mel_temperature_status_v1,state));
    RECORD(ams_mel_mfa_component_v1, FIELD(ams_mel_mfa_component_v1,component_id); FIELD(ams_mel_mfa_component_v1,state); FIELD(ams_mel_mfa_component_v1,temperature); FIELD(ams_mel_mfa_component_v1,installation_location_id); FIELD(ams_mel_mfa_component_v1,installation_details));
    RECORD(ams_mel_mfa_component_span_v1, FIELD(ams_mel_mfa_component_span_v1,data); FIELD(ams_mel_mfa_component_span_v1,size));
    RECORD(ams_mel_about_v1, FIELD(ams_mel_about_v1,model); FIELD(ams_mel_about_v1,serial_number); FIELD(ams_mel_about_v1,software_version); FIELD(ams_mel_about_v1,bootloader_software_version); FIELD(ams_mel_about_v1,hardware_version));
    RECORD(ams_mel_mfa_status_v1, FIELD(ams_mel_mfa_status_v1,state); FIELD(ams_mel_mfa_status_v1,state_description); FIELD(ams_mel_mfa_status_v1,mode_description); FIELD(ams_mel_mfa_status_v1,transition_status); FIELD(ams_mel_mfa_status_v1,about); FIELD(ams_mel_mfa_status_v1,components));
    RECORD(ams_mel_ir_subsystem_dep_info_v1, FIELD(ams_mel_ir_subsystem_dep_info_v1,subsystem_id); FIELD(ams_mel_ir_subsystem_dep_info_v1,criticality); FIELD(ams_mel_ir_subsystem_dep_info_v1,failure));
    RECORD(ams_mel_ir_subsystem_dep_info_span_v1, FIELD(ams_mel_ir_subsystem_dep_info_span_v1,data); FIELD(ams_mel_ir_subsystem_dep_info_span_v1,size));
    RECORD(ams_mel_ir_version_v1, FIELD(ams_mel_ir_version_v1,source); FIELD(ams_mel_ir_version_v1,major_revision); FIELD(ams_mel_ir_version_v1,minor_revision); FIELD(ams_mel_ir_version_v1,engineering_revision));
    RECORD(ams_mel_ir_subsystem_csci_info_v1, FIELD(ams_mel_ir_subsystem_csci_info_v1,csci); FIELD(ams_mel_ir_subsystem_csci_info_v1,mode); FIELD(ams_mel_ir_subsystem_csci_info_v1,version); FIELD(ams_mel_ir_subsystem_csci_info_v1,criticality); FIELD(ams_mel_ir_subsystem_csci_info_v1,failure); FIELD(ams_mel_ir_subsystem_csci_info_v1,bit_report); FIELD(ams_mel_ir_subsystem_csci_info_v1,connection_established));
    RECORD(ams_mel_ir_subsystem_csci_info_span_v1, FIELD(ams_mel_ir_subsystem_csci_info_span_v1,data); FIELD(ams_mel_ir_subsystem_csci_info_span_v1,size));
    RECORD(ams_mel_ir_subsystem_status_v1, FIELD(ams_mel_ir_subsystem_status_v1,subsystem_id); FIELD(ams_mel_ir_subsystem_status_v1,criticality); FIELD(ams_mel_ir_subsystem_status_v1,status_sequence_number); FIELD(ams_mel_ir_subsystem_status_v1,failure); FIELD(ams_mel_ir_subsystem_status_v1,subsystem_count); FIELD(ams_mel_ir_subsystem_status_v1,subsystems); FIELD(ams_mel_ir_subsystem_status_v1,csci_count); FIELD(ams_mel_ir_subsystem_status_v1,csci));
    RECORD(ams_mel_name_value_pair_v1, FIELD(ams_mel_name_value_pair_v1,name); FIELD(ams_mel_name_value_pair_v1,value)); RECORD(ams_mel_name_value_pair_span_v1, FIELD(ams_mel_name_value_pair_span_v1,data); FIELD(ams_mel_name_value_pair_span_v1,size));
    RECORD(ams_mel_security_artifact_v1, FIELD(ams_mel_security_artifact_v1,component_id); FIELD(ams_mel_security_artifact_v1,associated_id)); RECORD(ams_mel_security_artifact_span_v1, FIELD(ams_mel_security_artifact_span_v1,data); FIELD(ams_mel_security_artifact_span_v1,size));
    RECORD(ams_mel_security_event_v1, FIELD(ams_mel_security_event_v1,kind); FIELD(ams_mel_security_event_v1,category); FIELD(ams_mel_security_event_v1,details); FIELD(ams_mel_security_event_v1,subsystem_id); FIELD(ams_mel_security_event_v1,service_id); FIELD(ams_mel_security_event_v1,mdf_id));
    RECORD(ams_mel_security_audit_record_v1, FIELD(ams_mel_security_audit_record_v1,security_event_id); FIELD(ams_mel_security_audit_record_v1,event_timestamp_ns); FIELD(ams_mel_security_audit_record_v1,subsystem_id); FIELD(ams_mel_security_audit_record_v1,artifacts); FIELD(ams_mel_security_audit_record_v1,event); FIELD(ams_mel_security_audit_record_v1,outcome); FIELD(ams_mel_security_audit_record_v1,severity));
    RECORD(ams_mel_ir_health_metadata_event_v1, FIELD(ams_mel_ir_health_metadata_event_v1,kind); FIELD(ams_mel_ir_health_metadata_event_v1,mfa_status); FIELD(ams_mel_ir_health_metadata_event_v1,bit_status); FIELD(ams_mel_ir_health_metadata_event_v1,subsystem_status); FIELD(ams_mel_ir_health_metadata_event_v1,discrete_status); FIELD(ams_mel_ir_health_metadata_event_v1,security_audit); FIELD(ams_mel_ir_health_metadata_event_v1,mfa_status_detailed));
    LAYOUT(ams_mel_ir_c2_metadata *); LAYOUT(ams_mel_ir_c2_metadata_event *);
    LAYOUT(ams_mel_ir_image_metadata *); LAYOUT(ams_mel_ir_image_metadata_event *);
    LAYOUT(ams_mel_ir_channel_comms_request *); LAYOUT(ams_mel_ir_channel_capability *);
    LAYOUT(ams_mel_ir_health *); LAYOUT(ams_mel_ir_health_metadata *); LAYOUT(ams_mel_ir_health_metadata_event *);
    LAYOUT(ams_mel_ir_navigation_request *);

    VALUE(AMS_MEL_POSITION_SOLUTION_NOT_SET); VALUE(AMS_MEL_POSITION_SOLUTION_ALIGNING);
    VALUE(AMS_MEL_POSITION_SOLUTION_FREE_INERTIAL); VALUE(AMS_MEL_POSITION_SOLUTION_GPS);
    VALUE(AMS_MEL_POSITION_SOLUTION_BLENDED); VALUE(AMS_MEL_POSITION_SOLUTION_MAX_EXCLUSIVE);
    RECORD(ams_mel_north_east_down_v1, FIELD(ams_mel_north_east_down_v1,north); FIELD(ams_mel_north_east_down_v1,east); FIELD(ams_mel_north_east_down_v1,down));
    RECORD(ams_mel_attitude_rate_v1, FIELD(ams_mel_attitude_rate_v1,attitude_rate); FIELD(ams_mel_attitude_rate_v1,attitude_rate_time_ns));
    RECORD(ams_mel_position_velocity_covariance_v1,
        FIELD(ams_mel_position_velocity_covariance_v1,position_position_pn_pn);
        FIELD(ams_mel_position_velocity_covariance_v1,position_position_pn_pe);
        FIELD(ams_mel_position_velocity_covariance_v1,position_position_pn_pd);
        FIELD(ams_mel_position_velocity_covariance_v1,position_position_pe_pe);
        FIELD(ams_mel_position_velocity_covariance_v1,position_position_pe_pd);
        FIELD(ams_mel_position_velocity_covariance_v1,position_position_pd_pd);
        FIELD(ams_mel_position_velocity_covariance_v1,position_velocity_pn_vn);
        FIELD(ams_mel_position_velocity_covariance_v1,position_velocity_pn_ve);
        FIELD(ams_mel_position_velocity_covariance_v1,position_velocity_pn_vd);
        FIELD(ams_mel_position_velocity_covariance_v1,position_velocity_pe_ve);
        FIELD(ams_mel_position_velocity_covariance_v1,position_velocity_pe_vd);
        FIELD(ams_mel_position_velocity_covariance_v1,position_velocity_pd_vd);
        FIELD(ams_mel_position_velocity_covariance_v1,velocity_velocity_vn_vn);
        FIELD(ams_mel_position_velocity_covariance_v1,velocity_velocity_vn_ve);
        FIELD(ams_mel_position_velocity_covariance_v1,velocity_velocity_vn_vd);
        FIELD(ams_mel_position_velocity_covariance_v1,velocity_velocity_ve_ve);
        FIELD(ams_mel_position_velocity_covariance_v1,velocity_velocity_ve_vd);
        FIELD(ams_mel_position_velocity_covariance_v1,velocity_velocity_vd_vd));
    RECORD(ams_mel_navigation_report_v1,
        FIELD(ams_mel_navigation_report_v1,system_time_ns);
        FIELD(ams_mel_navigation_report_v1,state);
        FIELD(ams_mel_navigation_report_v1,latitude_rad);
        FIELD(ams_mel_navigation_report_v1,longitude_rad);
        FIELD(ams_mel_navigation_report_v1,altitude_m);
        FIELD(ams_mel_navigation_report_v1,attitude);
        FIELD(ams_mel_navigation_report_v1,attitude_rate);
        FIELD(ams_mel_navigation_report_v1,speed);
        FIELD(ams_mel_navigation_report_v1,acceleration);
        FIELD(ams_mel_navigation_report_v1,wander_angle_rad);
        FIELD(ams_mel_navigation_report_v1,magnetic_heading);
        FIELD(ams_mel_navigation_report_v1,altitude_msl);
        FIELD(ams_mel_navigation_report_v1,position_velocity_covariance_uncertainty));
    RECORD(ams_mel_ir_navigation_result_v1, FIELD(ams_mel_ir_navigation_result_v1,response); FIELD(ams_mel_ir_navigation_result_v1,error_code));
    LAYOUT(ams_mel_ir_instrumentation *); LAYOUT(ams_mel_ir_instrumentation_request *);
    LAYOUT(ams_mel_ir_instrumentation_metadata *);
    LAYOUT(ams_mel_ir_instrumentation_metadata_event *);
    VALUE(AMS_MEL_IR_PRIORITY_NORMAL); VALUE(AMS_MEL_IR_PRIORITY_DEBUG);
    VALUE(AMS_MEL_IR_INSTRUMENTATION_METADATA_REPORT);
    VALUE(AMS_MEL_IR_CHANNEL_INSTRUMENTATION);
    RECORD(ams_mel_ir_instrumentation_config_v1,
        FIELD(ams_mel_ir_instrumentation_config_v1,channel_id);
        FIELD(ams_mel_ir_instrumentation_config_v1,channel_type);
        FIELD(ams_mel_ir_instrumentation_config_v1,platform_id);
        FIELD(ams_mel_ir_instrumentation_config_v1,sensor_location));
    RECORD(ams_mel_ir_instrumentation_level_command_v1,
        FIELD(ams_mel_ir_instrumentation_level_command_v1,command_id);
        FIELD(ams_mel_ir_instrumentation_level_command_v1,priority));
    RECORD(ams_mel_ir_instrumentation_report_v1,
        FIELD(ams_mel_ir_instrumentation_report_v1,command_id);
        FIELD(ams_mel_ir_instrumentation_report_v1,size);
        FIELD(ams_mel_ir_instrumentation_report_v1,timestamp_ns);
        FIELD(ams_mel_ir_instrumentation_report_v1,priority));
    RECORD(ams_mel_ir_instrumentation_result_v1,
        FIELD(ams_mel_ir_instrumentation_result_v1,report);
        FIELD(ams_mel_ir_instrumentation_result_v1,error_code));
    RECORD(ams_mel_ir_instrumentation_metadata_event_v1,
        FIELD(ams_mel_ir_instrumentation_metadata_event_v1,kind);
        FIELD(ams_mel_ir_instrumentation_metadata_event_v1,report));

    LAYOUT(ams_mel_ir_track *);
    VALUE(AMS_MEL_IR_CHANNEL_IRST_TRACK);
    RECORD(ams_mel_ir_track_config_v1,
        FIELD(ams_mel_ir_track_config_v1,channel_id);
        FIELD(ams_mel_ir_track_config_v1,channel_type);
        FIELD(ams_mel_ir_track_config_v1,platform_id);
        FIELD(ams_mel_ir_track_config_v1,sensor_location));

    LAYOUT(ams_mel_ir_track_metadata *);
    LAYOUT(ams_mel_ir_track_metadata_event *);
    VALUE(AMS_MEL_IR_TRACK_STATE_IDLE); VALUE(AMS_MEL_IR_TRACK_STATE_DETECTED);
    VALUE(AMS_MEL_IR_TRACK_STATE_COAST); VALUE(AMS_MEL_IR_TRACK_STATE_DROPPED);
    VALUE(AMS_MEL_IR_TRACK_MODE_IDLE); VALUE(AMS_MEL_IR_TRACK_MODE_SCAN);
    VALUE(AMS_MEL_IR_TRACK_MODE_STARE);
    VALUE(AMS_MEL_IR_TRACK_METADATA_IRST_TRACK_REPORT);
    RECORD(ams_mel_ir_track_report_v1,
        FIELD(ams_mel_ir_track_report_v1,system_time_ns);
        FIELD(ams_mel_ir_track_report_v1,activity_id);
        FIELD(ams_mel_ir_track_report_v1,measured_ned);
        FIELD(ams_mel_ir_track_report_v1,measured_intensity);
        FIELD(ams_mel_ir_track_report_v1,measured_snr);
        FIELD(ams_mel_ir_track_report_v1,filtered_ned);
        FIELD(ams_mel_ir_track_report_v1,filtered_intensity);
        FIELD(ams_mel_ir_track_report_v1,filtered_snr);
        FIELD(ams_mel_ir_track_report_v1,range_m);
        FIELD(ams_mel_ir_track_report_v1,range_error_m);
        FIELD(ams_mel_ir_track_report_v1,spatial_extent_rad);
        FIELD(ams_mel_ir_track_report_v1,track_quality);
        FIELD(ams_mel_ir_track_report_v1,clutter);
        FIELD(ams_mel_ir_track_report_v1,age_ns);
        FIELD(ams_mel_ir_track_report_v1,state);
        FIELD(ams_mel_ir_track_report_v1,mode));
    RECORD(ams_mel_ir_track_metadata_event_v1,
        FIELD(ams_mel_ir_track_metadata_event_v1,kind);
        FIELD(ams_mel_ir_track_metadata_event_v1,track_report));

    LAYOUT(ams_mel_ir_track_update_request *);
    VALUE(AMS_MEL_IR_TRACK_STATUS_CREATE); VALUE(AMS_MEL_IR_TRACK_STATUS_UPDATE);
    VALUE(AMS_MEL_IR_TRACK_STATUS_PREDICT); VALUE(AMS_MEL_IR_TRACK_STATUS_DELETE);
    RECORD(ams_mel_ir_track_covariance_v1,
        FIELD(ams_mel_ir_track_covariance_v1,xx);
        FIELD(ams_mel_ir_track_covariance_v1,xy);
        FIELD(ams_mel_ir_track_covariance_v1,xz);
        FIELD(ams_mel_ir_track_covariance_v1,x_vx);
        FIELD(ams_mel_ir_track_covariance_v1,x_vy);
        FIELD(ams_mel_ir_track_covariance_v1,x_vz);
        FIELD(ams_mel_ir_track_covariance_v1,yy);
        FIELD(ams_mel_ir_track_covariance_v1,yz);
        FIELD(ams_mel_ir_track_covariance_v1,y_vx);
        FIELD(ams_mel_ir_track_covariance_v1,y_vy);
        FIELD(ams_mel_ir_track_covariance_v1,y_vz);
        FIELD(ams_mel_ir_track_covariance_v1,zz);
        FIELD(ams_mel_ir_track_covariance_v1,z_vx);
        FIELD(ams_mel_ir_track_covariance_v1,z_vy);
        FIELD(ams_mel_ir_track_covariance_v1,z_vz);
        FIELD(ams_mel_ir_track_covariance_v1,vx_vx);
        FIELD(ams_mel_ir_track_covariance_v1,vx_vy);
        FIELD(ams_mel_ir_track_covariance_v1,vx_vz);
        FIELD(ams_mel_ir_track_covariance_v1,vy_vy);
        FIELD(ams_mel_ir_track_covariance_v1,vy_vz);
        FIELD(ams_mel_ir_track_covariance_v1,vz_vz));
    RECORD(ams_mel_ir_track_data_update_v1,
        FIELD(ams_mel_ir_track_data_update_v1,platform_id);
        FIELD(ams_mel_ir_track_data_update_v1,capability_uuid);
        FIELD(ams_mel_ir_track_data_update_v1,activity_uuid);
        FIELD(ams_mel_ir_track_data_update_v1,track_id);
        FIELD(ams_mel_ir_track_data_update_v1,entity_uuid);
        FIELD(ams_mel_ir_track_data_update_v1,track_status);
        FIELD(ams_mel_ir_track_data_update_v1,time_of_validity_seconds);
        FIELD(ams_mel_ir_track_data_update_v1,time_of_last_update_seconds);
        FIELD(ams_mel_ir_track_data_update_v1,track_position_ecef);
        FIELD(ams_mel_ir_track_data_update_v1,track_velocity_ecef);
        FIELD(ams_mel_ir_track_data_update_v1,covariance);
        FIELD(ams_mel_ir_track_data_update_v1,maneuver_probability);
        FIELD(ams_mel_ir_track_data_update_v1,track_quality));
    RECORD(ams_mel_ir_track_update_result_v1,
        FIELD(ams_mel_ir_track_update_result_v1,status);
        FIELD(ams_mel_ir_track_update_result_v1,error_code));

    LAYOUT(ams_mel_ir_track_system_response_request *);
    RECORD(ams_mel_ir_system_track_data_response_v1,
        FIELD(ams_mel_ir_system_track_data_response_v1,system_time_ns);
        FIELD(ams_mel_ir_system_track_data_response_v1,command_id);
        FIELD(ams_mel_ir_system_track_data_response_v1,request_id);
        FIELD(ams_mel_ir_system_track_data_response_v1,track_id);
        FIELD(ams_mel_ir_system_track_data_response_v1,range_m);
        FIELD(ams_mel_ir_system_track_data_response_v1,range_rate_mps);
        FIELD(ams_mel_ir_system_track_data_response_v1,range_error_m);
        FIELD(ams_mel_ir_system_track_data_response_v1,range_rate_error_mps);
        FIELD(ams_mel_ir_system_track_data_response_v1,az_el_valid);
        FIELD(ams_mel_ir_system_track_data_response_v1,range_valid);
        FIELD(ams_mel_ir_system_track_data_response_v1,inertial_az_el);
        FIELD(ams_mel_ir_system_track_data_response_v1,az_el_error));
    RECORD(ams_mel_ir_track_system_response_result_v1,
        FIELD(ams_mel_ir_track_system_response_result_v1,status);
        FIELD(ams_mel_ir_track_system_response_result_v1,error_code));

    VALUE(ams_mel_get_abi_version(&version));
    VALUE(version.major); VALUE(version.minor);
    return 0;
}
